server:
  port: 8081

spring:
  application:
    name: inventory-service

aws:
  region: ap-south-1

  s3:
    bucket-name: warehouse-management-system-assets

dynamodb:
  product-table: wms-products

logging:
  level:
    root: INFO
    com.cosmos: DEBUG
